//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetMVCBlogApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentResponse
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Text { get; set; }
        public string Mail { get; set; }
        public bool isValid { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
